# Tomcat
server:
    tomcat:
        max-threads: 10
        min-spare-threads: 10
        uri-encoding: utf-8
    port: 8082

# mysql
spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://47.103.86.55:3306/annaru_queue?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&useSSL=false&serverTimezone=GMT%2B8
        username: root
        password: annaru_mysql
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    resources:
            static-locations: classpath:/static/,classpath:/views/

# Mybatis配置
mybatis:
    mapperLocations: classpath:mapper/**/*.xml

